# Copyright (C) 2017 Andrea Cervesato
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# when "required" is not defined, consider the value optional

map:
    description:
        required: true
        type: str
    name:
        required: true
        type: str
    version:
        required: true
        type: str
    author:
        required: true
        type: str
    protocols:
        required: true
        map:
            sftp:
                map:
                    address:
                        required: true
                        type: str
                    port:
                        required: true
                        type: int
                        range:
                            min: 1
                            max: 65535
                    user:
                        required: true
                        type: str
                    password:
                        required: true
                        type: str
                    timeout:
                        required: true
                        type: float
                        range:
                            min: 1.0
                            max: 120.0
            ssh:
                map:
                    address:
                        required: true
                        type: str
                    port:
                        required: true
                        type: int
                    user:
                        required: true
                        type: str
                    password:
                        required: true
                        type: str
                    timeout:
                        required: true
                        type: float
    deploy:
        map:
            protocol:
                required: true
                type: str
                pattern: ^sftp$
            delete:
                type: bool
            transfer:
                seq:
                    - map:
                        source:
                            required: true
                            type: str
                        dest:
                            required: true
                            type: str
                        type:
                            type: str
    execute:
        map:
            protocol:
                required: true
                type: str
                pattern: ^ssh$
            commands:
                seq:
                    - map:
                        script:
                            required: true
                            type: str
                        protocol:
                            type: str
                        passing:
                            type: str
                        failing:
                            type: str
    collect:
        map:
            protocol:
                required: true
                type: str
                pattern: ^sftp$
            transfer:
                seq:
                    - map:
                        source:
                            required: true
                            type: str
                        dest:
                            required: true
                            type: str
                        type:
                            type: str